DROP DATABASE IF EXISTS empresaMaterialInformatico;
CREATE DATABASE empresaMaterialInformatico CHARACTER SET utf8mb4;
USE empresaMaterialInformatico;

CREATE TABLE DEPARTAMENTO (
    ID_Departamento INT PRIMARY KEY,
    Nombre VARCHAR(70) NOT NULL
);

CREATE TABLE EMPLEADO (
    ID_Empleado INT PRIMARY KEY,
    DNI VARCHAR(9) NOT NULL,
    Nombre VARCHAR(30) NOT NULL,
    Apellido1 VARCHAR(30) NOT NULL,
    Apellido2 VARCHAR(30) NOT NULL,
    Telefono VARCHAR(9),
    DEPARTAMENTO_ID_Departamento INT NOT NULL,
    FOREIGN KEY (DEPARTAMENTO_ID_Departamento) REFERENCES DEPARTAMENTO(ID_Departamento),
    CHECK (CHAR_LENGTH(DNI) = 9),
    CHECK (CHAR_LENGTH(Telefono) = 9 OR Telefono IS NULL)
);

CREATE TABLE CLIENTE (
    ID_Cliente INT PRIMARY KEY,
    DNI VARCHAR(9) NOT NULL,
    Nombre VARCHAR(30) NOT NULL,
    Apellido1 VARCHAR(30) NOT NULL,
    Apellido2 VARCHAR(30),
    Telefono VARCHAR(9),
    CHECK (CHAR_LENGTH(DNI) = 9),
    CHECK (CHAR_LENGTH(Telefono) = 9 OR Telefono IS NULL)
);

CREATE TABLE DISPOSITIVO (
    ID_Dispositivo INT PRIMARY KEY,
    Nombre VARCHAR(30) NOT NULL,
    Precio DECIMAL(19,4) NOT NULL CHECK (Precio >= 0),
    Stock INT NOT NULL CHECK (Stock >= 0),
    Estado ENUM('Nuevo', 'Segunda Mano') NOT NULL
);

CREATE TABLE COMPONENTES (
    ID_Componente INT PRIMARY KEY,
    Descripcion VARCHAR(100) NOT NULL,
    Precio DECIMAL(19,4) NOT NULL CHECK (Precio >= 0),
    Stock INT NOT NULL CHECK (Stock >= 0)
);

CREATE TABLE CONSTA (
    COMPONENTES_ID_Componente INT NOT NULL,
    DISPOSITIVO_ID_Dispositivo INT NOT NULL,
    Cantidad INT NOT NULL CHECK (Cantidad > 0),
    PRIMARY KEY (COMPONENTES_ID_Componente, DISPOSITIVO_ID_Dispositivo),
    FOREIGN KEY (COMPONENTES_ID_Componente) REFERENCES COMPONENTES(ID_Componente),
    FOREIGN KEY (DISPOSITIVO_ID_Dispositivo) REFERENCES DISPOSITIVO(ID_Dispositivo)
);

CREATE TABLE COMPRA_DISPOSITIVOS (
    DISPOSITIVO_ID_Dispositivo INT NOT NULL,
    CLIENTE_ID_Cliente INT NOT NULL,
    EMPLEADO_ID_Empleado INT NOT NULL,
    Fecha VARCHAR(45) NOT NULL,
    Cantidad INT NOT NULL CHECK (Cantidad > 0),
    PRIMARY KEY (DISPOSITIVO_ID_Dispositivo, CLIENTE_ID_Cliente, EMPLEADO_ID_Empleado, Fecha),
    FOREIGN KEY (DISPOSITIVO_ID_Dispositivo) REFERENCES DISPOSITIVO(ID_Dispositivo),
    FOREIGN KEY (CLIENTE_ID_Cliente) REFERENCES CLIENTE(ID_Cliente),
    FOREIGN KEY (EMPLEADO_ID_Empleado) REFERENCES EMPLEADO(ID_Empleado)
);

CREATE TABLE COMPRA_COMPONENTES (
    COMPONENTES_ID_Componente INT NOT NULL,
    CLIENTE_ID_Cliente INT NOT NULL,
    EMPLEADO_ID_Empleado INT NOT NULL,
    Fecha VARCHAR(45) NOT NULL,
    Cantidad INT NOT NULL CHECK (Cantidad > 0),
    PRIMARY KEY (COMPONENTES_ID_Componente, CLIENTE_ID_Cliente, EMPLEADO_ID_Empleado, Fecha),
    FOREIGN KEY (COMPONENTES_ID_Componente) REFERENCES COMPONENTES(ID_Componente),
    FOREIGN KEY (CLIENTE_ID_Cliente) REFERENCES CLIENTE(ID_Cliente),
    FOREIGN KEY (EMPLEADO_ID_Empleado) REFERENCES EMPLEADO(ID_Empleado)
);
